version: '3'
services:
  bot:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ./config.yaml:/app/config.yaml

  redis:
    image: redis:6.2.14-alpine
    ports:
      - "6379:6379"